theme = "tokyonight_storm"
# theme = "material_palenight"

[editor]
line-number = "relative"
auto-save = true
mouse = true
bufferline = "multiple"
color-modes = true
true-color = true
end-of-line-diagnostics = "hint"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "error"
